version: "3.3"
services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - redis
  redis:
    image: "redislabs/rejson:latest"